# Generated by Django 2.1 on 2019-06-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'employeeee'},
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
