# Generated by Django 2.1 on 2019-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0002_auto_20190614_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=10),
        ),
    ]
