# Generated by Django 2.1 on 2019-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0003_auto_20190617_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.CharField(max_length=20),
        ),
    ]
